# These strings are printed when running vglist.rb, so we just format each line
# as a string in an array and then derive values from it.
missing = [
  "Lego Star Wars II: The Original Trilogy can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 116, Wikidata name: Lego Star Wars II Mobile, Wikidata ID: 55246)",
  "Star Wars: The Clone Wars can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 113, Wikidata name: Star Wars: The Clone Wars (2002 video game), Wikidata ID: 55232)",
  "Star Wars: The Empire Strikes Back can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 76, Wikidata name: Star Wars: The Empire Strikes Back (1982 video game), Wikidata ID: 54325)",
  "Star Wars: The Empire Strikes Back can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 78, Wikidata name: Star Wars: The Empire Strikes Back (1992 video game), Wikidata ID: 54329)",
  "Star Wars Episode I: The Phantom Menace can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 84, Wikidata name: Star Wars: Episode I – The Phantom Menace, Wikidata ID: 54338)",
  "Star Wars Episode II: Attack of the Clones can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 89, Wikidata name: Star Wars: Episode II – Attack of the Clones (video game), Wikidata ID: 54844)",
  "Toy Story 3: The Video Game can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 375, Wikidata name: Toy Story 3 (video game), Wikidata ID: 195280)",
  "King's Quest II: Romancing the Throne can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 348, Wikidata name: King's Quest II, Wikidata ID: 177459)",
  "Amnesia: Memories can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 356, Wikidata name: Amnesia, Wikidata ID: 182409)",
  "007: Everything or Nothing can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 317, Wikidata name: James Bond 007: Everything or Nothing, Wikidata ID: 161202)",
  "G.I. Joe: The Rise of Cobra can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 578, Wikidata name: G.I. Joe: The Rise of Cobra (video game), Wikidata ID: 288884)",
  "Age of Conan: Unchained can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 749, Wikidata name: Age of Conan, Wikidata ID: 392183)",
  "Oretachi ni Tsubasa wa Nai can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 767, Wikidata name: We Without Wings, Wikidata ID: 405362)",
  "Aion: The Tower of Eternity can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 771, Wikidata name: Aion (video game), Wikidata ID: 406414)",
  "Thrasher: Skate and Destroy can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 789, Wikidata name: Thrasher Presents Skate and Destroy, Wikidata ID: 429875)",
  "City Bus Simulator can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1247, Wikidata name: City Bus Simulator 2010, Wikidata ID: 614246)",
  "Full Auto can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1312, Wikidata name: Lil cal 64, Wikidata ID: 630026)",
  "Shin Megami Tensei: Devil Summoner 2: Raidou Kuzunoha vs. King Abaddon can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1261, Wikidata name: Devil Summoner 2: Raidou Kuzunoha vs. King Abaddon, Wikidata ID: 617257)",
  "Rhythm Hunter: HarmoKnight can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1302, Wikidata name: HarmoKnight, Wikidata ID: 626993)",
  "Beast Wars: Transformers can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1353, Wikidata name: Beast Wars: Transformers (video game), Wikidata ID: 639840)",
  "Omikron: The Nomad Soul can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1637, Wikidata name: The Nomad Soul, Wikidata ID: 738740)",
  "Minetest can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1577, Wikidata name: Minetest Game, Wikidata ID: 722334)",
  "Hoshizora no Memoria -Wish upon a Shooting Star- can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2093, Wikidata name: Hoshizora no Memoria, Wikidata ID: 864600)",
  "Saya no Uta can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2163, Wikidata name: The Song of Saya, Wikidata ID: 890707)",
  "Cybernator can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2228, Wikidata name: Assault Suits Valken 2, Wikidata ID: 910467)",
  "Professor Layton vs. Phoenix Wright: Ace Attorney can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2409, Wikidata name: Professor Layton vs. Ace Attorney, Wikidata ID: 957410)",
  "428: Fūsa Sareta Shibuya de can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2591, Wikidata name: 428 Shibuya Scramble, Wikidata ID: 1045444)",
  "Sonic the Hedgehog (2006) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2723, Wikidata name: Sonic the Hedgehog, Wikidata ID: 1068669)",
  "The King of Fighters 2003 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2750, Wikidata name: The King of Fighters 2003juegos, Wikidata ID: 1071749)",
  "Jinkō Shōjo can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2889, Wikidata name: Artificial Girl 2, Wikidata ID: 1117764)",
  "Insaniquarium can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 3161, Wikidata name: Q1187558, Wikidata ID: 1187558)",
  "Buster Bros. can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 3346, Wikidata name: Pang, Wikidata ID: 1276594)",
  "Mahōjin Guru Guru can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 3548, Wikidata name: Magical Circle Guru Guru, Wikidata ID: 1374301)",
  "Jinkō Shōjo can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 3689, Wikidata name: Artificial Girl 3, Wikidata ID: 1449082)",
  "Beach Volley can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 4749, Wikidata name: Beach Volley (video game), Wikidata ID: 2063211)",
  "We ♥ Katamari can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 5186, Wikidata name: We Love Katamari, Wikidata ID: 2268510)",
  "Guardian (1986) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 32144, Wikidata name: Guardian (1986 video game), Wikidata ID: 11301574)",
  "Monster Hunter Tri can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 5368, Wikidata name: Monster Hunter 3, Wikidata ID: 2312881)",
  "Darkwing Duck can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 5601, Wikidata name: Darkwing Duck (Capcom), Wikidata ID: 2381494)",
  "Fire Emblem: Mystery of the Emblem can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 6217, Wikidata name: Fire Emblem: Monshō no Nazo, Wikidata ID: 2565615)",
  "Seiken Densetsu 3 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 6296, Wikidata name: Trials of Mana, Wikidata ID: 2588801)",
  "Final Fantasy VII (unofficial Famicom version) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 6534, Wikidata name: Final Fantasy VII, Wikidata ID: 2647594)",
  "Agent (Cancel) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 6570, Wikidata name: Agent, Wikidata ID: 2661073)",
  "Alundra 2: A New Legend Begins can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 6579, Wikidata name: Alundra 2, Wikidata ID: 2663381)",
  "2004–05 UEFA Champions League can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 6637, Wikidata name: UEFA Champions League 2004-2005, Wikidata ID: 2689491)",
  "SimIsle: Missions in the Rainforest can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 175, Wikidata name: SimIsle, Wikidata ID: 63266)",
  "16 Ton can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 7039, Wikidata name: 16t, Wikidata ID: 2808850)",
  "Fight Night Champion can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 7578, Wikidata name: Champion, Wikidata ID: 2982191)",
  "Nadia: Megafunland can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 9165, Wikidata name: Tootuff: Megafunland, Wikidata ID: 3334881)",
  "One Piece: Unlimited Cruise 2 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 9237, Wikidata name: One Piece: Unlimited Cruise 2 – Awakening of a Hero, Wikidata ID: 3352638)",
  "The Lord of the Rings Online: Shadows of Angmar can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1285, Wikidata name: The Lord of the Rings Online, Wikidata ID: 623479)",
  "Sherlock Holmes Crimes & Punishments can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 11722, Wikidata name: Crimes & Punishments, Wikidata ID: 5185480)",
  "Cross Racing Championship Extreme 2005 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 12029, Wikidata name: Cross Racing Championship 2005, Wikidata ID: 5188379)",
  "Duck Maze can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 13156, Wikidata name: Duck, Wikidata ID: 5311460)",
  "Dead Space (mobile) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 13344, Wikidata name: Dead Space, Wikidata ID: 4037091)",
  "Daytona USA 2001 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 13343, Wikidata name: Daytona USA, Wikidata ID: 4037078)",
  "Dragon Slayer Jr: Romancia can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 13355, Wikidata name: Romancia: Dragon Slayer Jr, Wikidata ID: 5305282)",
  "R3 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 15783, Wikidata name: R3: The Art Of Rocketry, Wikidata ID: 7274705)",
  "Muscle Champion: Kinnikutō Kessen can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 16096, Wikidata name: Muscle Champion: Kinnikujima no Kessen, Wikidata ID: 6940287)",
  "Gremlins can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 16305, Wikidata name: Gremlins (video game), Wikidata ID: 5607342)",
  "Super Chinese Land 1-2-3 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 17205, Wikidata name: Super Chinese Land 1-2-3 Dash, Wikidata ID: 7642254)",
  "Scrolls can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 17825, Wikidata name: Caller's Bane, Wikidata ID: 7439285)",
  "Tweenies: Doodles' Bones can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 18961, Wikidata name: The Tweenies The Movie, Wikidata ID: 7857517)",
  "Videocart-12: Baseball can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 19215, Wikidata name: Fairchild Channel F Videocarts, Wikidata ID: 7928001)",
  "TV Tennis can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 19719, Wikidata name: TV Tennis Electrotennis, Wikidata ID: 11319564)",
  "Can Can Bunny can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 19881, Wikidata name: Can Can Bunny series, Wikidata ID: 10846654)",
  "Wittard: Nemesis of Ragnarok can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 19947, Wikidata name: Baron Wittard: Nemesis of Ragnarok, Wikidata ID: 8028545)",
  "3rd Super Robot Wars Z: Jigoku-hen can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 20643, Wikidata name: 3rd Super Robot Wars Z, Wikidata ID: 15565304)",
  "Spintires can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 21056, Wikidata name: CONVERGIA, Wikidata ID: 17300733)",
  "The Great Ace Attorney: The Adventures of Ryūnosuke Naruhodō can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 21154, Wikidata name: Dai Gyakuten Saiban: Naruhodou Ryuunosuke no Bouken, Wikidata ID: 17338571)",
  "Ore no Imōto ga Konna ni Kawaii Wake ga Nai Portable ga Tsuzuku Wake ga Nai can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 21464, Wikidata name: There's no Way 'My Little Sister Can't Be This Cute Portable' Could Continue, Wikidata ID: 16747020)",
  "LucasArts Archives can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 22120, Wikidata name: The LucasArts Archives, Wikidata ID: 17019278)",
  "Akumajou Dracula X: Chi no Rondo can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 5743, Wikidata name: Castlevania: Rondo of Blood, Wikidata ID: 2421908)",
  "God of War IV can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 23526, Wikidata name: Q18345138, Wikidata ID: 18345138)",
  "Yakuza 6: The Song of Life can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 23863, Wikidata name: Yakuza 6, Wikidata ID: 20983112)",
  "Doodle Army 2: Mini Militia can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 24390, Wikidata name: Mini milatia sanu, Wikidata ID: 28196452)",
  "Heroine's Quest can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 24682, Wikidata name: Heroine's Quest: The Herald of Ragnarok, Wikidata ID: 28405263)",
  "Arena of Valor can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 24670, Wikidata name: Wángzhě Róngyào, Wikidata ID: 28360116)",
  "Project Treasure can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 24861, Wikidata name: Lost Reavers, Wikidata ID: 18928680)",
  "Sakura no Mori † Dreamers can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 25020, Wikidata name: Sakuranomori Dreamers, Wikidata ID: 22129701)",
  "Home Sweet Home can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 25357, Wikidata name: Home Sweet Home Game, Wikidata ID: 55382144)",
  "Tour de France can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 25822, Wikidata name: Le Tour de France, Wikidata ID: 48528002)",
  "Dai Gyakuten Saiban 2 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 25902, Wikidata name: Dai Gyakuten Saiban 2: Naruhodō Ryūnosuke no Kakugo, Wikidata ID: 30894518)",
  "Spider-Man (2018) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 25933, Wikidata name: Spider-Man, Wikidata ID: 25340029)",
  "Wángzhě Róngyào can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 26226, Wikidata name: Arena of Valor, Wikidata ID: 55812491)",
  "fault - milestone two side:above can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 26301, Wikidata name: Fault Milestone Two, Wikidata ID: 31969684)",
  "Imagine: Animal Doctor can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 26315, Wikidata name: My Pet Hotel, Wikidata ID: 29907070)",
  "Kingdom Hearts 0.2: Birth by Sleep - A Fragmentary Passage can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 26486, Wikidata name: Kingdom Hearts 0.2 Birth by Sleep -A fragmentary passage-, Wikidata ID: 29453254)",
  "Rune can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 26596, Wikidata name: Rune II, Wikidata ID: 55662792)",
  "Hydorah can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 26727, Wikidata name: Super Hydorah, Wikidata ID: 55099204)",
  "Shōmetsu Toshi can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 26885, Wikidata name: Afterlost, Wikidata ID: 24873319)",
  "Love and Producer can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27025, Wikidata name: Mr Love: Queen's Choice, Wikidata ID: 48928484)",
  "NFL GameDay (video game) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27247, Wikidata name: NFL GameDay, Wikidata ID: 55624454)",
  "Peach Ball: Senran Kagura can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27563, Wikidata name: Senran Kagura: Peach Ball, Wikidata ID: 56043048)",
  "Jennifer Government: NationStates can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 29393, Wikidata name: NationStates, Wikidata ID: 63064)",
  "Monster Musume Online can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27725, Wikidata name: Everyday Life with Monster Girls Online, Wikidata ID: 25399688)",
  "Kotonoha Amrilato can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27667, Wikidata name: The Expression Amrilato, Wikidata ID: 38278928)",
  "Deltarune: Chapter 1 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27879, Wikidata name: Deltarune, Wikidata ID: 58045522)",
  "One Piece Unlimited Cruise 1: The Treasure Beneath the Waves can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27841, Wikidata name: One Piece: Unlimited Cruise 1 – The Treasure Beneath the Waves, Wikidata ID: 56826736)",
  "Tekken (2018 video game) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27855, Wikidata name: Tekken, Wikidata ID: 56863114)",
  "Serious Sam 4: Planet Badass can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 28197, Wikidata name: Serious Sam 4, Wikidata ID: 56307070)",
  "Eco (2018 video game) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 28194, Wikidata name: Eco, Wikidata ID: 56298056)",
  "Pikuniku can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 28760, Wikidata name: Pikuniku DEMO, Wikidata ID: 60774329)",
  "Itsuka no Memorajxo can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 28794, Wikidata name: Itsuka no Memoraĵo ~Kotonoha Amrilato~, Wikidata ID: 61037747)",
  "Islands of Nyne can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 28944, Wikidata name: Islands of Nyne: Battle Royale, Wikidata ID: 55080272)",
  "One Hour One Life for Mobile can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 29018, Wikidata name: You are Hope, Wikidata ID: 61983328)",
  "Skipper & Skeeto: The Alphabetic Games can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 29278, Wikidata name: Skipper & Skeeto: Alphabet Games, Wikidata ID: 62470783)",
  "8DAYS - Peace is our Business can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27812, Wikidata name: 8Days, Wikidata ID: 52028959)",
  "Hyperdevotion Noire: Goddess Black Heart can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 20730, Wikidata name: Chō Megami Shinkō Noire: Gekishin Black Heart, Wikidata ID: 15635717)",
  "The King of Fighters: Maximum Impact can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 793, Wikidata name: KOF: Maximum Impact, Wikidata ID: 431238)",
  "Albert Odyssey Gaiden: Legend of Eldean can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1079, Wikidata name: Albert Odyssey: Legend of Eldean, Wikidata ID: 578030)",
  "Star Wars: Battlefront can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 99, Wikidata name: Star Wars: Battlefront (2004 video game), Wikidata ID: 54859)",
  "Maken Shao: Demon Sword can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 545, Wikidata name: Maken X, Wikidata ID: 282450)",
  "True Golf: Wicked 18 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 792, Wikidata name: True Golf Classics: Wicked 18, Wikidata ID: 430868)",
  "Pirates of the Caribbean: Dead Man's Chest can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 335, Wikidata name: Pirates of the Caribbean: Dead Man's Chest (video game), Wikidata ID: 167359)",
  "ARMA: Combat Operations can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1131, Wikidata name: ARMA: Armed Assault, Wikidata ID: 590516)",
  "The Room can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 19159, Wikidata name: The Room Tribute, Wikidata ID: 7761479)",
  "BS Zelda no Densetsu Kodai no Sekiban can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 6709, Wikidata name: BS The Legend of Zelda: Ancient Stone Tablets, Wikidata ID: 2708122)",
  "Marvel Super Heroes In War of the Gems can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 8282, Wikidata name: Marvel Super Heroes: War of the Gems, Wikidata ID: 3130597)",
  "The Legend of Heroes: Zero no Kiseki can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 29762, Wikidata name: The Legend of Heroes: Trails of Zero, Wikidata ID: 63225345)",
  "Flashback: The Quest for Identity can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2524, Wikidata name: Flashback, Wikidata ID: 1001925)",
  "Infestation: Survivor Stories can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 6520, Wikidata name: Infestation: Survivor Stories Classic, Wikidata ID: 2641452)",
  "Black Mirror (2017 video game) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 26066, Wikidata name: Black Mirror, Wikidata ID: 55605561)",
  "Star Wars: The Empire Strikes Back can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 77, Wikidata name: Star Wars: The Empire Strikes Back (1985 video game), Wikidata ID: 54327)",
  "Dragon Quest Swords: The Masked Queen and the Tower of Mirrors can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 641, Wikidata name: Dragon Quest Swords, Wikidata ID: 339485)",
  "The Godfather: The Game can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 2980, Wikidata name: The Godfather, Wikidata ID: 1139696)",
  "Rick and Morty Simulator: Virtual Rick-ality can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 24041, Wikidata name: Rick and Morty: Virtual Rick-ality, Wikidata ID: 26812637)",
  "Custom Order Maid 3D 2 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 28507, Wikidata name: Custom Order Maid 3D2: It's a Night Magic, Wikidata ID: 54420812)",
  "Shower With Your Dad Simulator 2015: Do You Still Shower With Your Dad can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27033, Wikidata name: Shower With Your Dad Simulator 2015, Wikidata ID: 32020638)",
  "Sea bass can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 29431, Wikidata name: Sea Bass Fishing, Wikidata ID: 3476648)",
  "The Powerpuff Girls can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 29555, Wikidata name: The Powerpuff Girls: Chemical X-Traction, Wikidata ID: 10381711)",
  "American Dragon: Jake Long - Rise of the Huntsclan can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 29877, Wikidata name: Disney's American Dragon: Jake Long - Rise of the Huntsclan!, Wikidata ID: 11856168)",
  "Sune och hans Värld - Pussjakten can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 29879, Wikidata name: Sune och pussjakten, Wikidata ID: 63486895)",
  "Striker '96 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 30046, Wikidata name: Merkating, Wikidata ID: 60786431)",
  "Man of Medan can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 30378, Wikidata name: The Dark Pictures: Man of Medan, Wikidata ID: 63866855)",
  "007: Nightfire can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 315, Wikidata name: James Bond 007: Nightfire, Wikidata ID: 161188)",
  "Fugue on the Battlefield can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 30699, Wikidata name: Fuga: Melodies of Steel, Wikidata ID: 64830506)",
  "Remothered: Going Porcelain can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 30749, Wikidata name: Remothered: Broken Porcelain, Wikidata ID: 65040590)",
  "Project Sakura Wars can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 30911, Wikidata name: Sakura Wars, Wikidata ID: 62633255)",
  "Eve the 1st Burst Error can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 30886, Wikidata name: Burst Error: Eve The 1st., Wikidata ID: 63224903)",
  "Five Nights at Freddy's VR: Help Wanted can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 30966, Wikidata name: Five Nights at Freddy's: Help Wanted, Wikidata ID: 63049708)",
  "Final Fantasy XI: Online: Treasures of Aht Urhgan can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1482, Wikidata name: Final Fantasy XI, Wikidata ID: 678394)",
  "King's Quest VII: The Princeless Bride can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1070, Wikidata name: King's Quest VII, Wikidata ID: 574590)",
  "Phantasy Star IV: The End of the Millennium can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1301, Wikidata name: Phantasy Star IV, Wikidata ID: 626822)",
  "Stay Tuned for Danger can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 11072, Wikidata name: Nancy Drew: Stay Tuned for Danger, Wikidata ID: 4050079)",
  "Schizm III: Nemezis can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 31936, Wikidata name: Nemezis: Mysterious Journey III, Wikidata ID: 60764802)",
  "Bushi Seiryuuden: Futari no Yuusha can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 20128, Wikidata name: Bushi Seiryūden: Futari no Yūsha, Wikidata ID: 11191904)",
  "Hakuisei Renai Shoukougun can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 20814, Wikidata name: Nurse Love Syndrome, Wikidata ID: 11580371)",
  "zula game can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 31250, Wikidata name: Zula, Wikidata ID: 32860678)",
  "Project Resistance can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 31501, Wikidata name: Resident Evil: Resistance, Wikidata ID: 66969026)",
  "NFL 2K (video game) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 31728, Wikidata name: NFL 2K, Wikidata ID: 67389378)",
  "Star Trek Generations: Beyond the Nexus can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 21718, Wikidata name: Beyond the Nexus, Wikidata ID: 16248700)",
  "Dragon Quest Heroes: Yamiryuu to Sekaiju no Shiro can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 21990, Wikidata name: Dragon Quest Heroes: The World Tree's Woe and the Blight Below, Wikidata ID: 18054654)",
  "Fire Emblem: Genealogy of the Holy War can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 8047, Wikidata name: Fire Emblem: Seisen no Keifu, Wikidata ID: 3072796)",
  "Age of Empires II: The Age of Kings can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 44, Wikidata name: Age of Empires II, Wikidata ID: 34852)",
  "Star Wars Episode III: Revenge of the Sith can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 91, Wikidata name: Star Wars: Episode III – Revenge of the Sith (video game), Wikidata ID: 54846)",
  "Panzer Elite Action: Fields of Glory can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 345, Wikidata name: Panzer Elite, Wikidata ID: 174489)",
  "Fire Emblem: Heroes of Light and Shadow can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 31, Wikidata name: Fire Emblem: New Mystery of the Emblem, Wikidata ID: 24516)",
  "Star Trek: The Next Generation can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 9685, Wikidata name: Future's Past, Wikidata ID: 3496991)",
  "Ore no Imōto ga Konnani Kawaii Wake ga Nai Portable can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 21461, Wikidata name: My Little Sister Can't Be This Cute Portable, Wikidata ID: 16744859)",
  "F1 Super License: Nakajima Satoru can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1252, Wikidata name: Nakajima Satoru Kanshū F1 Super License, Wikidata ID: 615251)",
  "Shin Megami Tensei: Persona 4 can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1058, Wikidata name: Persona 4, Wikidata ID: 568609)",
  "The Legend of Heroes: Ao no Kiseki can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 29764, Wikidata name: The Legend of Heroes: Trails of Blue, Wikidata ID: 63225347)",
  "Persona 5: Dancing in Starlight can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 27957, Wikidata name: Persona 5: Dancing Star Night, Wikidata ID: 41801533)",
  "Taiko no Tatsujin: Drum 'n' Fun! can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 17521, Wikidata name: Taiko no Tatsujin, Wikidata ID: 7676037)",
  "MediEvil (2019) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 28828, Wikidata name: MediEvil, Wikidata ID: 60099491)",
  "Red Orchestra 2: Heroes of Stalingrad can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 755, Wikidata name: Rising Storm/Red Orchestra 2 GOTY, Wikidata ID: 392678)",
  "Hyperdimension Neptunia Victory/Hyperdimension Neptunia Re;Birth3 V Generation can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 11525, Wikidata name: Hyperdimension Neptunia Victory, Wikidata ID: 4121008)",
  "The Legend Of Heroes: Trails of Cold Steel can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 21948, Wikidata name: Nerves of Steel, Wikidata ID: 18154748)",
  "Danganronpa AE: Ultra Despair Girls can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 21101, Wikidata name: Danganronpa Another Episode: Ultra Despair Girls, Wikidata ID: 15933494)",
  "Keitai Denjū Telefang Speed Version can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 11526, Wikidata name: Keitai Denjū Telefang, Wikidata ID: 4121427)",
  "LEGO Island Xtreme Stunts can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 15876, Wikidata name: Island Xtreme Stunts, Wikidata ID: 6083460)",
  "Ace Attorney Investigations 2: Prosecutor's Path can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 4509, Wikidata name: Gyakuten Kenji 2, Wikidata ID: 1998765)",
  "Boring Man - Online Tactical Stickman Combat can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 33946, Wikidata name: Boring Man, Wikidata ID: 93489886)",
  "Norn9: Var Commons can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 7437, Wikidata name: NΘRN9, Wikidata ID: 2914021)",
  "A Kiss For The Petals - Remembering How We Met can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 7567, Wikidata name: A Kiss For The Petals, Wikidata ID: 2979679)",
  "Higurashi When They Cry Hou - Ch.1 Onikakushi can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist. (vglist ID: 1629, Wikidata name: Higurashi When They Cry, Wikidata ID: 737271)",
]

regex = /(.*) can be matched based on its Wikidata ID, but the name on Wikidata differs from the one on vglist\. \(vglist ID: (\d+), Wikidata name: (.*), Wikidata ID: (\d+)\)/

missing_objs = []
missing.each do |missing_line|
  missing_line.scan(regex) do |match|
    missing_objs << {
      vglist_id: match[1].to_i,
      vglist_url: "https://vglist.co/games/#{match[1]}",
      vglist_name: match[0],
      wikidata_id: match[3].to_i,
      wikidata_url: "https://www.wikidata.org/wiki/Q#{match[3]}",
      wikidata_name: match[2]
    }
  end
end

require 'json'
puts JSON.pretty_generate(missing_objs)
