# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'mediawiki_api-wikidata', github: 'wmde/WikidataApiGem'
gem 'mediawiki_api'
gem 'sparql-client'
gem 'dotenv'
