require "mediawiki_api"

client = MediawikiApi::Client.new "https://pcgamingwiki.com/w/api.php"
client.log_in ENV["PCGW_USERNAME"], ENV["PCGW_PASSWORD"]

pcgw_ids = ["Hidden_Expedition:_Titanic", "Exodus_from_the_Earth", "Catacomb_Snatch", "Dungeon_Defenders_Eternity", "Mitos.is:_The_Game", "East_Tower_-_Kurenai", "East_Tower_-_Akio", "1..._2..._3..._KICK_IT!_(Drop_That_Beat_Like_an_Ugly_Baby)", "Hustle_Cat", "Dreadhalls", "RWBY:_Grimm_Eclipse", "Hounds:_The_Last_Hope", "Victory_and_Glory:_Napoleon", "World's_Dawn", "Zavix_Tower", "Sky_to_Fly:_Faster_Than_Wind", "Subterrain", "Lost_Lands:_Mahjong", "Frontiers", "Euclidean", "Selfie_Tennis", "Unseen_Diplomacy", "Minigolf_VR", "Light_Repair_Team_4", "Gon'_E-Choo!", "Modbox", "Bowslinger", "InMind_VR", "Gumball_Drift", "Water_Bears_VR", "A-10_VR", "XLR", "Minigame_Party_VR", "World_of_Diving", "Chunks", "Fishing_Planet", "Gunslinger_Trainer", "Polaris_Sector", "Master_Spy", "Zombie_Training_Simulator", "Airships:_Conquer_the_Skies", "LiEat", "Airport_Madness_3D", "Pro_Gamer_Manager", "The_Men_of_Yoshiwara:_Kikuya", "Savage_Lands", "Primal_Fears", "Hacker_Evolution", "Unholy_Heights", "Colony_Survival", "Sonya:_The_Great_Adventure", "Shadows:_Price_For_Our_Sins_Bonus_Edition", "Realm_Grinder", "Sumer", "Shop_Heroes", "Liftoff", "Yu-Gi-Oh!_Legacy_of_the_Duelist", "Kindergarten", "Ancient_Space", "Intergalactic_Bubbles", "Little_Cells", "Space_Xonix", "Heavy_Gear_Assault", "How_to_Survive_2", "Interstellar_Rift", "Front_Defense", "Tokyo_Twilight_Ghost_Hunters_Daybreak:_Special_Gigs", "The_Journey_Down:_Chapter_One", "The_Journey_Down:_Chapter_Three", "Sundered", "The_Gateway_Trilogy", "NotCoD", "Battle_Mages:_Sign_of_Darkness", "SphereFACE", "Exanima", "Aftercharge", "Trianga's_Project:_Battle_Splash_2.0", "Badland_Bandits", "Fidel_Dungeon_Rescue", "My_Free_Zoo", "The_Jackbox_Party_Pack_4", "Afterparty", "Loot_Box_Simulator_20!8", "Azkend_2:_The_World_Beneath", "Gaben_Kingdom", "Train_Journey", "Colonumbers", "Mahjong_Roadshow", "Play_with_Gilbert", "Shiftlings", "Food_Truck_VR", "Vertical_Fall", "Wizard_Warz"]

first_batch = pcgw_ids[0..48]

client.action :purge, titles: first_batch.join('|')
