# Returns the platforms and genres as lists of wikidata IDs
SELECT ?item ?itemLabel (group_concat(distinct ?platform;separator=", ") as ?platforms) (group_concat(distinct ?genre;separator=", ") as ?genres) with {
  SELECT ?item WHERE 
  {
    ?item wdt:P31 wd:Q7889 .
  } LIMIT 10 } as %i
WHERE
{ 
  include %i
  ?item wdt:P400 ?p1.
  ?item wdt:P136 ?g1.
  bind(strafter(str(?p1), "http://www.wikidata.org/entity/") as ?platform)
  bind(strafter(str(?g1), "http://www.wikidata.org/entity/") as ?genre)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
} group by ?item ?itemLabel
